name: build-test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: ^1.15

      - name: go info
        shell: bash
        run: |
          echo $(go version) at $(which go)
          echo go version: $(go version)
          echo cache: $(ls $RUNNER_TOOL_CACHE/go)

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{GOPATH}}/src/github.com/${{ github.repository }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Get Protocol Buffers
        shell: bash
        run: |
          cd ${{GOPATH}}/src/github.com/${{ github.repository }}
          ./scripts/get-protobuf.sh

      - name: Get google/api/annotations.proto dependencies
        shell: bash
        run: |
          cd ${{GOPATH}}/src/github.com/${{ github.repository }}
          ./scripts/get-api-deps.sh

      - name: Build
        shell: bash
        run: |
          cd ${{GOPATH}}/src/github.com/${{ github.repository }}
          make all
